weather_task:
  description: >
    Use the weather_forecast_tool to get the weather forecast for the requested day ({day}) for the requested city ({city}).
  expected_output: >
    A clear, friendly, and readable weather forecast for the requested city on the requested day.
  agent: weather_agent