hello_world_task:
  description: >
    Greet the user.greet them using their name (e.g., "Hello John!").
    Keep the tone friendly and brief.
    Do not perform any other tasks. The name is {name}
  expected_output: >
    - If no name is provided: "Hi there! What's your name?"
    - If a name is provided: "Hello {name}!"
  agent: hello_world_agent
  variables:
    - name: name
      description: The user's name, if provided.