web_search_task:
  description: >
    Use the Serper tool to search the web for up-to-date information related to the user's query: {query}.
  expected_output: >
    A list of relevant facts, news, or web results.
  agent: web_search_agent

information_compiler_task:
  description: >
    Compile and synthesize information from the web search and other sources into a structured, easy-to-read summary about: {query}
  expected_output: >
    A synthesized summary or report combining all relevant findings.
  agent: information_compiler_agent
  dependencies:
    - web_search_task

research_task:
  description: >
    Review the outputs from the Web Search Agent and the Information Compiler Agent regarding: {query}.
    Synthesize all findings into a single, comprehensive, and well-structured answer for the user.
    Do NOT describe your process or what you plan to do—just present the final answer as if you are directly answering the user's question.
  expected_output: >
    A concise, actionable, and well-structured answer for the user, based on all available findings.
  agent: research_agent
  dependencies:
    - web_search_task
    - information_compiler_task